apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sslmonitors.nabinchhetri.com
spec:
  scope: Namespaced
  group: nabinchhetri.com
  names:
    kind: SSLMonitor
    plural: sslmonitors
    singular: sslmonitor
    shortNames:
      - ssl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                domain_name:
                  type: string
                  description: The name of the domain/website.
                googlechat_webhook_url:
                  type: string
                  description: It takes the googlechat webhook url to send alerts.
                alert_threshold_days:
                  type: integer
                  description: It takes the number of  threshold days for ssl expiry to send alerts.
                  default: 30
                expiry_date:
                  type: string
                  description: The date of domain ssl expiry.
              required:
                - domain_name
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
      additionalPrinterColumns:
        - name: DomainName
          type: string
          priority: 0
          jsonPath: .spec.domain_name
          description: The name of the domain/website.
        - name: "Alert Threshold Days"
          type: integer
          priority: 0
          jsonPath: .spec.alert_threshold_days
          description: It outputs the number of threshold days for ssl expiry to send alerts.
        - name: ExpiryDate
          type: string
          priority: 0
          jsonPath: .metadata.annotations.ExpiryDate
          description: The date of domain ssl expiry.
        - name: DaysRemaining
          type: string
          priority: 0
          jsonPath: .metadata.annotations.DaysRemaining
          description: The number of days left to expire ssl of a domain.