apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: ssl-operator
  template:
    metadata:
      labels:
        application: ssl-operator
    spec:
      serviceAccountName: sslmonitor-sa
      containers:
        - name: sslmonitoring
          image: nabinchhetri/sslmonitor:v1.0.9