---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sslmonitor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sslmonitor-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]

  # Framework: admission webhook configuration management.
  - apiGroups: ["admissionregistration.k8s.io/v1", "admissionregistration.k8s.io/v1"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["create", "patch"]


  - apiGroups: ["nabinchhetri.com"]
    resources: ["sslmonitors"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sslmonitor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sslmonitor-role
subjects:
- kind: ServiceAccount
  name: sslmonitor-sa
  namespace: default